DATASET_SOURCE:

##TEST TEMP SAMPLE
# -
#   DESIGN_FOLDER: thub_s1423
#   SUB_TYPE: s13207_T482
#   SOURCE_FILE: s1423_T400
#   LIB_FOLDER: cell_lib2
#   LIB_FILE_NAME: lec25dscc25.v
#   LOGIC_LEVEL: NA
#   ASSIGN_REPLACE: 1
#   SCANFF_REPLACE: 1
#   STRLOGIC_REPLACE: 0
#   TRUSTHUB_LIB: 1
#   EMBED_SOURCE: 1
#   DETECT_SOURCE: 0
#   TRAIN_SOURCE: 0
##TEST TEMP SAMPLE

 -
   DESIGN_FOLDER: original_designs
   SUB_TYPE: c2670
   SOURCE_FILE: c2670
   LIB_FOLDER: cell_lib2
   LIB_FILE_NAME: lec25dscc25.v
   LOGIC_LEVEL: NA
   ASSIGN_REPLACE: 1
   SCANFF_REPLACE: 1
   STRLOGIC_REPLACE: 0
   TRUSTHUB_LIB: 1
   EMBED_SOURCE: 1
   DETECT_SOURCE: 0
   TRAIN_SOURCE: 0

 -
   DESIGN_FOLDER: original_designs
   SUB_TYPE: c3540
   SOURCE_FILE: c3540
   LIB_FOLDER: cell_lib2
   LIB_FILE_NAME: lec25dscc25.v
   LOGIC_LEVEL: NA
   ASSIGN_REPLACE: 1
   SCANFF_REPLACE: 1
   STRLOGIC_REPLACE: 0
   TRUSTHUB_LIB: 1
   EMBED_SOURCE: 1
   DETECT_SOURCE: 0
   TRAIN_SOURCE: 0
 -
   DESIGN_FOLDER: original_designs
   SUB_TYPE: c5315
   SOURCE_FILE: c5315
   LIB_FOLDER: cell_lib2
   LIB_FILE_NAME: lec25dscc25.v
   LOGIC_LEVEL: NA
   ASSIGN_REPLACE: 1
   SCANFF_REPLACE: 1
   STRLOGIC_REPLACE: 0
   TRUSTHUB_LIB: 1
   EMBED_SOURCE: 1
   DETECT_SOURCE: 0
   TRAIN_SOURCE: 0

 -
   DESIGN_FOLDER: original_designs
   SUB_TYPE: c6288
   SOURCE_FILE: c6288
   LIB_FOLDER: cell_lib2
   LIB_FILE_NAME: lec25dscc25.v
   LOGIC_LEVEL: NA
   ASSIGN_REPLACE: 1
   SCANFF_REPLACE: 1
   STRLOGIC_REPLACE: 0
   TRUSTHUB_LIB: 1
   EMBED_SOURCE: 1
   DETECT_SOURCE: 0
   TRAIN_SOURCE: 0
 -
   DESIGN_FOLDER: original_designs
   SUB_TYPE: s1423scan
   SOURCE_FILE: s1423scan
   LIB_FOLDER: cell_lib2
   LIB_FILE_NAME: lec25dscc25.v
   LOGIC_LEVEL: NA
   ASSIGN_REPLACE: 1
   SCANFF_REPLACE: 1
   STRLOGIC_REPLACE: 0
   TRUSTHUB_LIB: 1
   EMBED_SOURCE: 1
   DETECT_SOURCE: 0
   TRAIN_SOURCE: 0
 -
   DESIGN_FOLDER: original_designs
   SUB_TYPE: s13207scan
   SOURCE_FILE: s13207scan
   LIB_FOLDER: cell_lib2
   LIB_FILE_NAME: lec25dscc25.v
   LOGIC_LEVEL: NA
   ASSIGN_REPLACE: 1
   SCANFF_REPLACE: 1
   STRLOGIC_REPLACE: 0
   TRUSTHUB_LIB: 1
   EMBED_SOURCE: 1
   DETECT_SOURCE: 0
   TRAIN_SOURCE: 0
 -
   DESIGN_FOLDER: original_designs
   SUB_TYPE: s15850scan
   SOURCE_FILE: s15850scan
   LIB_FOLDER: cell_lib2
   LIB_FILE_NAME: lec25dscc25.v
   LOGIC_LEVEL: NA
   ASSIGN_REPLACE: 1
   SCANFF_REPLACE: 1
   STRLOGIC_REPLACE: 0
   TRUSTHUB_LIB: 1
   EMBED_SOURCE: 1
   DETECT_SOURCE: 0
   TRAIN_SOURCE: 0

 -
   DESIGN_FOLDER: original_designs
   SUB_TYPE: s35932scan
   SOURCE_FILE: s35932scan
   LIB_FOLDER: cell_lib2
   LIB_FILE_NAME: lec25dscc25.v
   LOGIC_LEVEL: NA
   ASSIGN_REPLACE: 1
   SCANFF_REPLACE: 1
   STRLOGIC_REPLACE: 0
   TRUSTHUB_LIB: 1
   EMBED_SOURCE: 1
   DETECT_SOURCE: 0
   TRAIN_SOURCE: 0

#======FOR DETECTION MODEL==========================
# -
#   DESIGN_FOLDER: thub_s1423
#   SUB_TYPE: s1423_T426
#   SOURCE_FILE: s1423_T426
#   LIB_FOLDER: cell_lib2
#   LIB_FILE_NAME: lec25dscc25.v
#   LOGIC_LEVEL: NA
#   ASSIGN_REPLACE: 1
#   SCANFF_REPLACE: 1
#   STRLOGIC_REPLACE: 0
#   TRUSTHUB_LIB: 1
#   EMBED_SOURCE: 1
#   DETECT_SOURCE: 1
#
# -
#   DESIGN_FOLDER: thub_s1423
#   SUB_TYPE: s1423_T424
#   SOURCE_FILE: s1423_T424
#   LIB_FOLDER: cell_lib2
#   LIB_FILE_NAME: lec25dscc25.v
#   LOGIC_LEVEL: NA
#   ASSIGN_REPLACE: 1
#   SCANFF_REPLACE: 1
#   STRLOGIC_REPLACE: 0
#   TRUSTHUB_LIB: 1
#   EMBED_SOURCE: 1
#   DETECT_SOURCE: 1

EXTRA_DATASET_SOURCE:
  ENABLE: True
  FOLDER: sample_info
  CONFIG_FILE: samples_yaml.yaml
  INFCSV_FILE: samples_info.csv


WORD2VEC_PARA:
  FOLDER: word2vec_emb
  SET_FILE: final_embedset.csv
  SET_LENG: 0
  OUT_LOG: word2vectrainer_netlist
  OUT_MODEL: word2vec_model.pth
  OUT_FILE: PGP_out.vec

DETECT_PARA:
  TEST_PARA:
    FOLDER: word2vec_emb
    SET_FILE: final_test.csv
    SET_LENG: 0

  TRAIN_PARA:
    FOLDER: word2vec_emb
    SET_FILE: final_train.csv
    SET_LENG: 0
    SET_LABELS_CNT: 0

    SET_EPOCH_FILE: NA
    SET_EPOCH_LENG: NA
    SET_EPOCH_LABELS_CNT: NA

  PROCS_PARA:
    FOLDER: word2vec_emb
    OUT_LOG: nnclassifier
    OUT_ANA_FILE: score_pred_label_comp.csv
    OUT_MODEL: classifier_model.pth

SAVE_PARA:
  FOLDER: word2vec_emb
  # ==To be filled by program
  DEBUG_MODE: NA
  LOGIC_LEVEL: NA
  YAML_CONFIG: NA
  REGEN_YAML: NA
  K_FOLD_ENA: NA
  K_FOLD_NUM: NA
  FIX_TYPE_ENA: NA
  FIX_TYPE_LST: NA
  EACH_TYPE_NUM: NA
  SAMPLE_CONFIG: NA
  TEST_SET_ENA: NA
  PROCS_QUEUE: NA
  SAMPLE_DIRS: NA






#  OUT_FILE: PGP_out.vec